### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by LuigiR0jas** [TelosLabs/rails-world#1]
https://lucid.app/lucidchart/559bc490-f723-4cf5-a3f4-5ecd33b8cf53/edit?useCachedRole=false&docId=559bc490-f723-4cf5-a3f4-5ecd33b8cf53&shared=true&page=0_0&invitationId=inv_d02c6a2f-f1a1-4d2a-a869-911701f3a3ae#

**Comment by michaelmcintyre** [comment]
Is the design public?
