### ISSUE TITLE
Add "show password" button

### ISSUE THREAD

**Issue by LuigiR0jas** [TelosLabs/rails-world#111]
## Requirements
1. Add "show password" for password fields from [Stimulus Components](https://www.stimulus-components.com/docs/stimulus-password-visibility)
2. Use icons from the [Iconicool library](https://www.figma.com/design/EfcJC7mbsROsAfPqSGg2wC/App-Design?node-id=902-11869&t=ovjV9bmqMind0tNV-0)

**Comment by wuletawwonte** [comment]
Hi @LuigiR0jas
This issue has been implemented and can now be closed.
