### ISSUE TITLE
Report bug functionality

### ISSUE THREAD

**Issue by LuigiR0jas** [TelosLabs/rails-world#59]
## Requirements
1. Create bug report model in the DB
2. Implement report bug section in the Sponsor view according to designs
3. Implement bug report form
4. Once the bug report form is submitted, a bug report is created and user is redirected to the sponsor view with a flash message

## Design
1. https://www.figma.com/design/EfcJC7mbsROsAfPqSGg2wC/App-Design?node-id=545-5569&t=vZ6R06RaDN0N1NST-0

**Comment by wuletawwonte** [comment]
I would love to work on this feature. But, I couldn't find the mentioned page in the Figma Design.

**Comment by LuigiR0jas** [comment]
@wuletawwonte Ah, yes. We ended up reworking the "About" page entirely and removing it. Apologies for the confusion!
